services:
  remix-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remix-dev
    volumes:
      - ./remix-app:/app
      - remix_app_node_modules:/app/node_modules
    ports:
      - "3000:3000"  # Remix development server
      - "5173:5173"  # Vite development server (if needed)
    environment:
      - NODE_ENV=development
    command: >
      bash -c "
        if [ ! -d node_modules ] || [ ! -f package.json ]; then
          echo 'Creating new Remix project from scratch...'
          # Use npx directly instead of a globally installed remix
          npx create-remix@latest --template remix-run/indie-stack .
        fi &&
        echo 'Installing dependencies...' &&
        pnpm install &&
        echo 'Setting up Prisma...' &&
        npx prisma generate &&
        echo 'Starting development server...' &&
        # Use npx to run the locally installed remix
        npx remix dev
      "
    tty: true
    stdin_open: true

volumes:
  remix_app_node_modules: