services:
  remix-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remix-dev
    volumes:
      - ./remix-app:/app
      - remix_app_node_modules:/app/node_modules
    ports:
      - "3000:3000"  # Remix development server
      - "5173:5173"  # Vite development server (if needed)
    environment:
      - NODE_ENV=development
    command: >
      bash -c "
        if [ ! -d node_modules ]; then
          if [ ! -f package.json ]; then
            echo 'Creating new Remix project...'
            npx create-remix@latest . --template remix-run/indie-stack
          fi
          echo 'Installing dependencies...'
          pnpm install
        fi &&
        echo 'Starting development server...' &&
        # Run dev command from the project's package.json
        # This ensures we use the locally installed Remix version
        pnpm run dev
      "
    tty: true
    stdin_open: true
    # This line makes the container use the host's network interface
    # Helpful for some network-related issues on macOS or WSL
    # network_mode: "host"  # Uncomment if needed for specific environments

volumes:
  remix_app_node_modules: